kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: devnet
nodes:
- role: control-plane
  extraPortMappings:
  # Yelb App
  - containerPort: 30001
    hostPort: 8080
    protocol: TCP
  # Sock-Shop App
  - containerPort: 30201
    hostPort: 8081
    protocol: TCP
- role: worker
- role: worker
- role: worker
- role: worker